### PR TITLE
vga and hdmi improvements

### LINKED ISSUE #5: Add pr_warn to hdmi.c
Add warnings if hdmi infoframe unpack fails.

### PR DESCRIPTION
**Pull request by awesomelewis2007**
## hdmi: add pr_warn if infoframe unpack fails
Closes #5 
- Add pr_warn if infoframe unpack fails if
    - infoframe is too large
    - infoframe is invaild
    - infoframe checksum is invaild

- Changed functions:
    - hdmi_avi_infoframe_unpack
    - hdmi_spd_infoframe_unpack
    - hdmi_audio_infoframe_unpack
    - hdmi_vendor_any_infoframe_unpack
    - hdmi_drm_infoframe_unpack_only
    - hdmi_drm_infoframe_unpack
    - hdmi_infoframe_unpack
## vga: Add documentation to vgastate and vga
Add documentation to better understand code.

### CODE REVIEW

File: drivers/video/hdmi.c [hunk 1]
```diff
@@ -29,6 +29,7 @@
 #include <linux/hdmi.h>
 #include <linux/string.h>
 #include <linux/device.h>
+#include <linux/kernel.h>
```
Comment (awesomelewis2007) [inline drivers/video/hdmi.c:32]: Needed for `pr_warn()`
